### ISSUE TITLE
bug: handle wrong password and display an error message when confirming transaction

### ISSUE THREAD

**Issue by Sednaoui** [Sednaoui/Candide#71]
When confirming a transaction, a user needs to add their password to decrypt their wallet and sign. Currently, the wallet does not display a message if the password is wrong. We would want display a message to the user and ask them to reattempt to enter their password without closing the modal

**Comment by khan-mujeeb** [comment]
i will like to work on this issue

**Comment by Sednaoui** [comment]
Feel free to get started! You can follow the read-me in the wallet folder. If you need help setting up or more clarification, reach out on [twitter](https://twitter.com/candidewallet) and I will share a discord so we can chat

**Comment by Sednaoui** [comment]
closing this since this has been fixed in the last commits
